import { SidebarComponent } from "@/components/sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "XeeAI",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-row min-h-screen">
      <SidebarProvider>
        <SidebarComponent /> {/* Render the sidebar itself */}
        <main className="flex-1 flex flex-col">
          <SidebarTrigger /> {/* Button or trigger to toggle sidebar */}
          <div className="flex-1 flex items-center justify-center">
            {children}
          </div>
        </main>
      </SidebarProvider>
    </div>
  );
}
