import { Metadata } from "next";
import { Instrument_Serif, Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"

// New primary fonts
const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  variable: "--font-instrument",
  weight: ["400"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// Legacy fonts (kept for compatibility)
const sentient = localFont({
  src: "./fonts/sentient.ttf",
  variable: "--font-sentient",
});

export const metadata: Metadata = {
  title: "XeeAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${instrumentSerif.variable} ${inter.variable} ${sentient.variable} scroll-smooth`}
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="antialiased bg-gradient-to-br from-xai-lightcyan to-white dark:from-xai-federal dark:to-xai-marian">
        <div className="flex flex-col min-h-screen ">{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
